name: flashtorch
channels:
  - pytorch
dependencies:
  - python=3.6
  - ipykernel=5.1.3
  - numpy=1.17.3
  - pillow=6.2.1
  - pytest-cov=2.8.1
  - pytest-mock=1.11.2
  - pytorch=1.3.1
  - scipy=1.3.1
  - torchvision=0.4.2
